package edu.drexel.psal.anonymouth.suggestors;

public enum HighlightMapList {
	
	None, SENTENCES_SHORTER_THAN_TARGET, SENTENCES_LONGER_THAN_TARGET,
	EIGHT_SYLLABLE_WORDS, SEVEN_SYLLABLE_WORDS, SIX_SYLLABLE_WORDS, FIVE_SYLLABLE_WORDS, FOUR_SYLLABLE_WORDS, THREE_SYLLABLE_WORDS,
	TWO_SYLLABLE_WORDS, SINGLE_SYLLABLE_WORDS, ALL_DIGITS, SPECIFIC_DIGITS, SPECIFIC_FUNCTION_WORDS, SPECIFIC_LETTER, SPECIFIC_WITHOUT_LETTER,
	SPECIFIC_MISSPELLED_WORDS, SPECIFIC_LETTER_BIGRAMS, 
	SPECIFIC_LETTER_TRIGRAMS, UNIQUE_WORDS,  REPEATED_WORDS, SPECIFIC_WORD_BIGRAMS, SPECIFIC_WORD_TRIGRAMS, SPECIFIC_WORDS,


	// SPECIFIC_POS_BIGRAMS, SPECIFIC_POS_TAGS, SPECIFIC_POS_TRIGRAMS,SHORTER_THAN_TARGET_WORDS, LONGER_THAN_TARGET_WORDS,,
} 